datagrid:
    embedded-forms-grid:
        source:
            type: orm
            query:
                select:
                    - embedded_form.id
                    - embedded_form.title
                    - embedded_form.formType
                    - channel.name as channelName
                from:
                    - { table: Oro\Bundle\EmbeddedFormBundle\Entity\EmbeddedForm, alias: embedded_form }
                join:
                    left:
                        - { join: embedded_form.channel, alias: channel }
        columns:
            title:
                label: oro.embedded_form.title.label
            formType:
                label: oro.embedded_form.form_type.label
            channelName:
                label: oro.embedded_form.channel.label
        properties:
            id: ~
            update_link:
                type:       url
                route:      oro_embedded_form_update
                params:     [ id ]
            delete_link:
                type:       url
                route:      oro_embedded_form_delete
                params:     [ id ]
            view_link:
                type:       url
                route:      oro_embedded_form_view
                params:     [ id ]
        actions:
            view:
                type: navigate
                label: View
                icon: user
                link: view_link
                rowAction: true
            update:
                type: navigate
                label: Update
                icon: edit
                link: update_link
            delete:
                type: delete
                label: Delete
                icon: trash
                link: delete_link
