datagrid:
    embedded-forms-grid:
        source:
            type: orm
            query:
                select:
                    - embedded_form.formType
                    - channel.name as channelName
                from:
                    - { table: Oro\Bundle\EmbeddedFormBundle\Entity\EmbeddedFormEntity, alias: embedded_form }
                join:
                    left:
                        - { join: embedded_form.channel, alias: channel }

        columns:
            formType:
                label: oro.ebemedded_form.form_type
            channelName:
                label: oro.channel.name


    contact-requests-grid:
        source:
            type: orm
            query:
                select:
                    - contact_request.name
                    - contact_request.email
                    - contact_request.phone
                    - channel.name as channelName
                from:
                    - { table: Oro\Bundle\EmbeddedFormBundle\Entity\ContactRequestEntity, alias: contact_request }
                join:
                    left:
                        - { join: contact_request.channel, alias: channel }

        columns:
            name:
                label: oro.contact_request.name
            email:
                label: oro.contact_request.email
            phone:
                label: oro.contact_request.phone
            channelName:
                label: oro.channel.name