datagrid:
    embedded-forms-grid:
        source:
            type: orm
            query:
                select:
                    - embedded_form.formType
                    - channel.name as channelName
                from:
                    - { table: Oro\Bundle\EmbeddedFormBundle\Entity\EmbeddedFormEntity, alias: embedded_form }
                join:
                    left:
                        - { join: embedded_form.channel, alias: channel }

        columns:
            formType:
                label: oro.ebemedded_form.form_type
            channelName:
                label: oro.channel.name