oro_menu_config:
    items:
        embedded_forms:
            label: 'Embedded Forms'
            route: 'oro_embedded_form_list'

    tree:
        application_menu:
            children:
                system_tab:
                    children:
                        embedded_forms: ~