oro_menu_config:
    items:
        embedded_forms:
            label: Embedded Forms
            route: oro_embedded_form_list
            extras:
                routes: ['oro_embedded_form_*']
    tree:
        application_menu:
            children:
                system_tab:
                    children:
                        embedded_forms: ~

oro_titles:
    oro_embedded_form_list:    ~
    oro_embedded_form_view:    %%form.title%%
    oro_embedded_form_create:  Create embedded form
    oro_embedded_form_update:  %%form.title%% - Edit
