layout:
    actions:
        - '@add':
            id:        embedded_form
            parentId:  content
            blockType: embed_form_fields
            options:
                form_name: embedded_form

    conditions: 'context["embedded_form_custom_layout"]==""'

