oro_layout:
    actions:
        - @add:
            id:          head
            parentId:    root
            blockType:   head
            options:
                title:   Form
        - @add:
            id:          meta_charset
            parentId:    head
            blockType:   meta
            options:
                charset: 'utf-8'
        - @add:
            id:          meta_x_ua_compatible
            parentId:    head
            blockType:   meta
            options:
                http_equiv: 'X-UA-Compatible'
                content:    'IE=edge,chrome=1'
        - @add:
            id:          meta_viewport
            parentId:    head
            blockType:   meta
            options:
                name:    'viewport'
                content: 'width=device-width, initial-scale=1.0'
        - @add:
            id:          base_css
            parentId:    head
            blockType:   style
        - @add:
            id:          form_css
            parentId:    head
            blockType:   style
            options:
                content: { @value: $context.embedded_form_entity.css }
        - @add:
            id:          content
            parentId:    root
            blockType:   body
        - @setBlockTheme:
            themes: 'OroEmbeddedFormBundle:Layout:embed_form.html.twig'
