oro_layout:
    actions:
        - @add:
            id:        form
            parent:    content
            blockType: embed_form_legacy_form
            options:
                form:        { @value: $context.embedded_form.view }
                form_layout: { @value: $context.embedded_form_custom_layout }
